# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21f86028cf6979e9b3c687cfaefe6ea498f3a00158ca9f561a6788b0d68c77d71329111911f8d6037a80532ce35e990c1fb0821177e90bc19f7425036e29f992

test:
  secret_key_base: fd8eda72c37e0a083724394b0bebc5fa9685edd649a74223aba545e9ad7677d0155cd6a1d37bd3420a7db3a7aacbe231dfea6f5c631892bba2e99b1c0f167e91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
