# Create a 'settings.yml' file in this directory with the following settings filled in.

development:
  wunderground_api_key: 'API_KEY' # get a free key here: https://www.wunderground.com/weather/api/
  gmail_address: 'EMAIL@gmail.com' # only gmail is supported at the moment
  gmail_password: 'PASSWORD'

test:
  wunderground_api_key: 'API_KEY'
  gmail_address: 'EMAIL@gmail.com'
  gmail_password: 'PASSWORD'
